#!/usr/bin/env bash
# This script displays username, UID, and Home directory from /etc/passwd

while IFS=":" read -r username _ uid _ _ home shell; do
  echo "Username: $username"
  echo "UID: $uid"
  echo "Home Directory: $home"
done < /etc/passwd
